# release-drafter の設定ファイル
# 日付ベースのリリースタグを使用 (release/YYYY-MM-DD)
# name と tag はワークフローで直接指定するため、ここでは設定不要
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '⬆️ Dependencies'
    labels:
      - 'dependencies'
      - 'deps'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
# 日付ベースのリリースではバージョン番号は使用しないため、version-resolverは不要
# version-resolver:
#   major:
#     labels:
#       - 'major'
#   minor:
#     labels:
#       - 'minor'
#       - 'feature'
#       - 'enhancement'
#   patch:
#     labels:
#       - 'patch'
#       - 'fix'
#       - 'bugfix'
#       - 'bug'
#       - 'chore'
#       - 'maintenance'
#       - 'documentation'
#       - 'dependencies'
#   default: patch
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS