name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate release date
        id: date
        run: |
          # 日本時間で日付を取得 (UTC+9)
          echo "date=$(TZ='Asia/Tokyo' date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          
      - name: Create Release Draft
        uses: release-drafter/release-drafter@v6
        with:
          name: "Release ${{ steps.date.outputs.date }}"
          tag: "release/${{ steps.date.outputs.date }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}